### ISSUE TITLE
All sites are currently appearing in the iCal export 

### ISSUE THREAD

**Issue by natbat** [natbat/pillarpointstewards#181]

**Comment by simonw** [comment]
https://www.pillarpointstewards.com/shifts/calendar-instructions/ is the page linking to the shift calendars.

**Comment by simonw** [comment]
URLs: https://github.com/natbat/pillarpointstewards/blob/b0768349ddcb30ce2cd678fc5914aba8f6fcae01/pillarpointstewards/config/urls.py#L36-L37

Python code: https://github.com/natbat/pillarpointstewards/blob/b0768349ddcb30ce2cd678fc5914aba8f6fcae01/pillarpointstewards/shifts/views.py#L276-L299

Tests: https://github.com/natbat/pillarpointstewards/blob/b0768349ddcb30ce2cd678fc5914aba8f6fcae01/pillarpointstewards/shifts/tests.py#L70-L88

**Comment by simonw** [comment]
Yeah, neither of those `ics` view functions attempt to filter by membership.

**Comment by simonw** [comment]
The fix is now live. You will now see all shifts from all teams you are a member of - so if you are only a member of one team you'll only get one set of shifts.

Maybe we should have separate URLs for each team though? Natalie and I are members of multiple teams but we only want Pillar Point shifts in our calendars.
